# Generated by Django 4.2.3 on 2023-08-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='authorUser',
            new_name='author_user',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='ratingAuthor',
            new_name='rating_author',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nameCat',
            new_name='name_cat',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentPost',
            new_name='comment_post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentUser',
            new_name='comment_user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='dateComment',
            new_name='date_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='textComment',
            new_name='text_comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='authorPost',
            new_name='author_post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categoryType',
            new_name='category_type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='datePost',
            new_name='date_post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='postCategory',
            new_name='post_category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='textPost',
            new_name='text_post',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='categoryThrough',
            new_name='category_through',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='postThrough',
            new_name='post_through',
        ),
    ]
